//-----------------
#ifndef CONTADOR_H
#define CONTADOR_H
//-----------------
/********************************************
inc_cont: Funci¢n que incrementa el contador*
que se encuentra en contador.c como objeto  *
********************************************/
void inc_cont(void);
/********************************************
leer_cont: Funci¢n que devuelve el valor del*
contador que se encuentra en contador.c     *
como objeto  				    *
********************************************/
unsigned int leer_cont(void);
/********************************************
reset_cont: Funci¢n que resetea el contador *
que se encuentra en contador.c como objeto  *
********************************************/
void reset_cont(void);
#endif
//----------------